### ISSUE TITLE
"error caught in async handler" when searching

### ISSUE THREAD

**Issue by Gelio** [gelguy/wilder.nvim#199]
Hey, for some time (around 2 weeks) I started noticing the following errors when `wilder.nvim` is running:

```
error caught in async handler '/Users/grzegorz.rozdzialik/.local/share/nvim/lazy/wilder.nvim/rplugin/python3/wilder:function:_wilder_python_search [[{'session_id': 1, 'handler_id': 4, 'input': '', 'run_id': 1}, {}, '()\\w*']]'
Traceback (most recent call last):
  File "/Users/grzegorz.rozdzialik/.local/share/nvim/lazy/wilder.nvim/rplugin/python3/wilder/__init__.py", line 272, in _search
    self.run_in_background(self.search_handler, args + [self.cached_buffer['buffer']])
  File "/Users/grzegorz.rozdzialik/.local/share/nvim/lazy/wilder.nvim/rplugin/python3/wilder/__init__.py", line 82, in run_in_background
    return self.executor.submit(functools.partial( fn, *([event] + args), ))
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'submit'
```

<img width="2097" alt="image" src="https://github.com/gelguy/wilder.nvim/assets/889383/8d93e830-d0bf-4094-8aa5-4100e6b59376">

In this case, I just opened up `nvim` (new empty file) and started searching. The moment I pressed `/`, I got this error. This error also re-appears later as I am typing during search.

From time to time, this error also appears in cmdline completions for commands (`:`). Sometimes, I get this error both in `:` and `/`. Other times, just in `/`.

Running `:UpdateRemotePlugins` a few times and then restarting Neovim sometimes helps with this error. Still, it re-appears after some time. I haven't found the exact reproduction steps (whether it is running `nvim` in a different directory, or updating plugins, or rebuilding Neovim from source).

`:checkhealth provider.python`:

```

==============================================================================
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set. Searching for python3 in the environment.
- Executable: /opt/homebrew/bin/python3
- Python version: 3.11.7
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

```

My config:

```lua
 	{
		"Gelio/wilder.nvim",
		branch = "fix-last-arg-completion-for-lua",
		config = function()
			vim.cmd.runtime("wilder.vim")

			vim.cmd.call("wilder#main#start()")
		end,
		build = ":UpdateRemotePlugins",
		event = "CmdlineEnter",
	},
```

https://github.com/Gelio/ubuntu-dotfiles/blob/609a0fc3f17f3175b14ae1a2fa64cce8da769428/universal/neovim/config/nvim/lua/plugins/init.lua#L19-L29

I am running the code from https://github.com/gelguy/wilder.nvim/pull/166 which is ahead of `master` by 1 commit (3 lines of code).

**Comment by Gelio** [comment]
I haven't seen this error for quite some time (over 2 weeks). I'm not sure what happened. I will close this issue
